export enum EnumModals{
    COMMIT_CONTEXT="COMMIT_CONTEXT",
    CONTEXT="CONTEXT",
    CREATE_BRANCH="CREATE_BRANCH",
    ERROR="ERROR",
    CONFIRMATION="CONFIRMATION",
    PUSH_TO="PUSH_TO",
    PULL_FROM="PULL_FROM",
    CHECKOUT="CHECKOUT",
    TOAST="TOAST",
}