export enum EnumHtmlIds{
    branchPanel="branchPanel",
    branchSvgContainer="branchSvgContainer",
    branchPanelContainer="branchPanelContainer",
    branchVerticalScrollBar="branchVerticalScrollBar",
    branchHorizontalScrollBar="horizontalScrollBar",    
    modifiedChangesPanel="modifiedChangesPanel",
    stagedChangesPanel="stagedChangesPanel",
    conflictedChangesPanel="conflictedChangesPanel",
    stage_unstage_allPanel="unstage_unstage_allPanel",
    unstage_unstage_allPanel="unstage_unstage_allPanel",
    acceptIncomingCurrentAllPanel="acceptIncomingCurrentAllPanel",
    diffview_container = "diffview_container",
    CommitDiff = "CommitDiff",
    ConflictEditorTopPanel = "ConflictEditorTopPanel",
    ConflictEditorBottomPanel = "ConflictEditorBottomPanel",
}